---
name: Release datasync-agent-vm-shutdown
on:
  push:
    tags: ['*']
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: |-
          pip3 install --target datasync-agent-vm-shutdown azure-mgmt-compute azure-identity
          cd datasync-agent-vm-shutdown
          zip -r ../datasync-agent-vm-shutdown.zip .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: datasync-agent-vm-shutdown.zip
